name: nc_controller
description: "Aplicación de control para figuras customizadas con Arduino y Bluetooth de Naboo Customs"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2  # Agrega esta línea
  path_provider: ^2.1.1  # Agrega esta línea



  # Iconos de Cupertino
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.4.0

  # Gestión de estado
  provider: ^6.1.2

  # Networking y caché de imágenes
  cached_network_image: ^3.4.1
  http: ^1.2.2

  # Servicios de imágenes
  cloudinary_public: ^0.23.1
  image_picker: ^1.1.2

  # Audio
  just_audio: ^0.9.42

  # Bluetooth - CORREGIDO
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1

  # UI y utilidades
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

  # Marquee y texto scrolleable
  marquee: ^2.2.3

  # WebView para Instagram
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/
    - assets/audio/
    - assets/icons/

