name: nc_controller
description: "Aplicación Controladora Naboo Customs"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.0
  firebase_storage: ^11.4.0

  # Manejo de estado
  provider: ^6.1.1

  # UI y animaciones
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  shimmer: ^3.0.0

  # Bluetooth (comentado temporalmente por problemas de compilación)
  # flutter_bluetooth_serial: ^0.4.0

  # Integraciones externas
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # Iconos
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/
    - assets/iconos/
    - assets/animaciones/

  # fonts:
  #   - family: Orbitron
  #     fonts:
  #       - asset: assets/fuentes/Orbitron-Regular.ttf
  #       - asset: assets/fuentes/Orbitron-Bold.ttf
  #         weight: 700