name: nc_controller
description: "Aplicación Controladora Naboo Customs"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  marquee: ^2.2.3

  # Firebase - VERSIONES ESTABLES Y COMPATIBLES
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5

  # Manejo de estado - VERSION FIJA PARA EVITAR PROBLEMAS
  provider: ^6.1.5

  # UI y animaciones
  google_fonts: ^6.2.1
  lottie: ^2.7.0
  shimmer: ^3.0.0

  # Integraciones externas
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # NUEVAS DEPENDENCIAS PARA CLOUDINARY
  cloudinary_public: ^0.23.1
  http: ^1.4.0
  dio: ^5.4.0

  # BLUETOOTH DEPENDENCIES
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1

  # AUDIO PLAYER PARA MUSICA
  just_audio: ^0.9.40

  # Iconos
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/
    - assets/iconos/
    - assets/animaciones/

# IMPORTANTE: Configuración adicional para evitar errores de nested
dependency_overrides:
  # Forzar versión específica de nested para evitar conflictos
  nested: ^1.0.0

  # Permisos (para Bluetooth)
  permission_handler: ^11.3.1

  # Iconos
  cupertino_icons: ^1.0.8

  webview_flutter: ^4.4.2