// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDNRLR-9F6dZLLQglWV_miHreLr-tHJiA',
    appId: '1:119227194371:web:629c2dcad57bdae1d7c236',
    messagingSenderId: '119227194371',
    projectId: 'nccontroller-78de1',
    authDomain: 'nccontroller-78de1.firebaseapp.com',
    storageBucket: 'nccontroller-78de1.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDNRLR-9F6dZLLQglWV_miHreLr-tHJiA',
    appId: '1:119227194371:android:629c2dcad57bdae1d7c236',
    messagingSenderId: '119227194371',
    projectId: 'nccontroller-78de1',
    storageBucket: 'nccontroller-78de1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADErLs5ycoi6JZ_AkfNGv5eZ5ZRmykvLc',
    appId: '1:119227194371:ios:5fefa44460ebe7c7d7c236',
    messagingSenderId: '119227194371',
    projectId: 'nccontroller-78de1',
    storageBucket: 'nccontroller-78de1.firebasestorage.app',
    iosBundleId: 'com.naboocustoms.nccontroller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADErLs5ycoi6JZ_AkfNGv5eZ5ZRmykvLc',
    appId: '1:119227194371:ios:5fefa44460ebe7c7d7c236',
    messagingSenderId: '119227194371',
    projectId: 'nccontroller-78de1',
    storageBucket: 'nccontroller-78de1.firebasestorage.app',
    iosBundleId: 'com.naboocustoms.nccontroller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDNRLR-9F6dZLLQglWV_miHreLr-tHJiA',
    appId: '1:119227194371:web:629c2dcad57bdae1d7c236',
    messagingSenderId: '119227194371',
    projectId: 'nccontroller-78de1',
    authDomain: 'nccontroller-78de1.firebaseapp.com',
    storageBucket: 'nccontroller-78de1.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}